language: node_js
node_js:
  - 16

services:
  - docker

install:
  -echo "Everyting is ok"

script:
  - docker --version
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker tag udagram-reverseproxy zgnmgg/udagram-reverseproxy
  - docker tag udagram-api-feed zgnmgg/udagram-api-feed
  - docker tag udagram-api-user zgnmgg/udagram-api-user
  - docker tag udagram-frontend zgnmgg/udagram-frontend

after_sucess:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push zgnmgg/udagram-reverseproxy
  - docker push zgnmgg/udagram-api-user
  - docker push zgnmgg/udagram-api-feed
  - docker push zgnmgg/udagram-frontend
